# Generated by Django 5.1.5 on 2025-06-04 09:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("studybuddy_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="status",
        ),
        migrations.DeleteModel(
            name="Status",
        ),
    ]
