# Generated by Django 5.1.5 on 2025-06-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studybuddy_app", "0002_remove_profile_status_delete_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
